name: Manual ASAN
on:                                                                             
  workflow_dispatch:                                                            

jobs:
  manual_asan:
    name: Manual (ASAN)
    uses: ./.github/workflows/ci-build.yml
    with:
      jobtype: 'triggered'
      subtype: 'asan'
      runtype: 'simple'
