name: Manual ASAN
on:
  workflow_dispatch:

jobs:
  manual_asan:
    name: Manual (ASAN)
    uses: ./.github/workflows/ci-build.yml
    with:
      jobtype: 'manual'
      subtype: 'asan'
      runtype: 'simple'
      FAILURE_SUFFIX: 'manual-asan'
